# action.yml
name: 'pike is for permissions'
description: 'Pike is for permissions!'
branding:
  icon: 'activity'
  color: 'green'

inputs:
  file:  
    description: 'file to scan'
  directory:  
    description: 'Directory to scan'  
  verb:  
    description: 'The Pike action or verb to use: e.g. scan'
    default: scan    
  auto:  
    description: 'Appends Policy to Readme'   
  init:  
    description: 'Run Terraform init to download modules'     
  output:  
    description: 'Output types e.g. json terraform'    
  write:
    description: 'Flag to write policy to file'   
runs:
  using: 'docker'
  image: 'docker://jameswoolfenden/pike:v0.2.18'
  args:
    - ${{ inputs.file }}
    - ${{ inputs.directory }}
    - ${{ inputs.verb }}
    - ${{ inputs.auto }}
    - ${{ inputs.write }}
    - ${{ inputs.init }}
    - ${{ inputs.output }}
