on:
  push:
    branches:
      - master
  workflow_dispatch:
  repository_dispatch:

jobs:
  pike_is_for_permissions:
    runs-on: ubuntu-latest
    name: pike
    steps:
      - uses: actions/checkout@v2
      - name: Version
        id: version
        uses: JamesWoolfenden/action-pike@latest
        with:
          action: version
      - name: Scan
        id: scan
        uses: JamesWoolfenden/action-pike@latest
        with:
          directory: 'test'
          action: scan


      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.scan.outputs.time }}"
